"""deleted functionallity

Revision ID: 52dc766c278c
Revises: 7b6a93bc3cfa
Create Date: 2019-05-28 16:22:03.897933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dc766c278c'
down_revision = '7b6a93bc3cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'downvote')
    op.drop_column('pitch', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
